model:
  model_path: Qwen/Qwen2-VL-7B-Instruct
  optimizer:
    lr: 1.0e-5
    lr_decay_style: cosine
  accelerator:
    init_device: meta
    ulysses_size: 1
    fsdp_config:
      fsdp_mode: fsdp2

data:
  train_path: configs/multimodal/data/tulu_sharegpt4v_llavavideo.yaml
  chat_template: qwen2vl
  max_seq_len: 2048
  train_size: 80000000
  mm_configs:
    image_max_pixels: 602112 # 28 * 28 * 768
    video_max_pixels: 602112 # 28 * 28 * 768
    max_frames: 16
    fps: 2.0
    use_audio_in_video: false

train:
  wandb:
    project: qwen2vl
    name: qwen2vl
  freeze_vit: false
  num_train_epochs: 2
  micro_batch_size: 1
  global_batch_size: 32
  max_steps: 2000
  checkpoint:
    output_dir: qwen2vl_sft
